/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type {
	GardenAssociatedPartialsResult,
	GardenCreateCommand,
	GardenFullByKeyQueryOpParams,
	GardenFullSchema,
	GardenMembershipAcceptCommand,
	GardenMembershipCreateCommand,
	GardenMembershipDeleteCommand,
	GardenMembershipRevokeCommand,
	GardenMembershipRoleChangeCommand,
	GardenMostRelevantPartialsQueryOpParams,
	GardenPartialSchema,
	GardenPartialsByKeysQueryOpParams,
	GardenPendingInvitesResult,
	GardenUniqueKeyResult
} from '../../types';
import { axiosClient } from '../../../data/customAxios';

/**
 * Accepts a Garden Membership.
 * @summary Garden membership invitiation acceptance.
 */
export const gardenMembershipAcceptCommandOp = (
	gardenMembershipAcceptCommand: GardenMembershipAcceptCommand
) => {
	return axiosClient<void>({
		url: `/gardens/command/accept_invite`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: gardenMembershipAcceptCommand
	});
};
/**
 * Changes the role on another's Garden Membership.
 * @summary Garden Membership role change.
 */
export const gardenMembershipRoleChangeCommandOp = (
	gardenMembershipRoleChangeCommand: GardenMembershipRoleChangeCommand
) => {
	return axiosClient<void>({
		url: `/gardens/command/change_role`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: gardenMembershipRoleChangeCommand
	});
};
/**
 * Creates a new Garden and invites requested users.
 * @summary Garden creation.
 */
export const gardenCreateCommandOp = (gardenCreateCommand: GardenCreateCommand) => {
	return axiosClient<void>({
		url: `/gardens/command/create`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: gardenCreateCommand
	});
};
/**
 * Creates new Garden Memberships and sends email confirmation emails.
 * @summary Garden membership invitiation.
 */
export const gardenMembershipCreateCommandOp = (
	gardenMembershipCreateCommand: GardenMembershipCreateCommand
) => {
	return axiosClient<void>({
		url: `/gardens/command/invite`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: gardenMembershipCreateCommand
	});
};
/**
 * Removes one's own Garden Membership from a garden.
 * @summary Garden membership deletion.
 */
export const gardenMembershipDeleteCommandOp = (
	gardenMembershipDeleteCommand: GardenMembershipDeleteCommand
) => {
	return axiosClient<void>({
		url: `/gardens/command/leave`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: gardenMembershipDeleteCommand
	});
};
/**
 * Removes another's Garden Membership from a garden.
 * @summary Removes a user from a garden.
 */
export const gardenMembershipRevokeCommandOp = (
	gardenMembershipRevokeCommand: GardenMembershipRevokeCommand
) => {
	return axiosClient<void>({
		url: `/gardens/command/revoke`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: gardenMembershipRevokeCommand
	});
};
/**
 * Returns a partial representation of all gardens that are associated with the client
 * @summary Returns a partial representation of all gardens that are associated with the client
 */
export const gardenAssociatedPartialsQueryOp = () => {
	return axiosClient<GardenAssociatedPartialsResult>({
		url: `/gardens/query/associated_partials`,
		method: 'GET'
	});
};
/**
 * Returns a full representation of gardens given by a key.
 * @summary Returns a full representation of a garden by its key.
 */
export const gardenFullByKeyQueryOp = (params: GardenFullByKeyQueryOpParams) => {
	return axiosClient<GardenFullSchema>({
		url: `/gardens/query/full_by_key`,
		method: 'GET',
		params
	});
};
/**
 * Generates a unique garden key given a plant name and a random string.
 * @summary Generate a new, unique garden key.
 */
export const gardenGenerateUniqueKeyQueryOp = () => {
	return axiosClient<GardenUniqueKeyResult>({
		url: `/gardens/query/generate_unique_key`,
		method: 'GET'
	});
};
/**
 * Returns a partial representation of most relevant gardens to the user, ordered by relevance.
 * @summary Returns a partial representation of most relevant gardens to the user.
 */
export const gardenMostRelevantPartialsQueryOp = (
	params: GardenMostRelevantPartialsQueryOpParams
) => {
	return axiosClient<GardenPartialSchema[]>({
		url: `/gardens/query/most_relevant`,
		method: 'GET',
		params
	});
};
/**
 * Returns a partial representation of gardens given by keys, provided they exist and the client is authorized to use them.
 * @summary Returns a partial representation of gardens given by keys.
 */
export const gardenPartialsByKeysQueryOp = (
	params: GardenPartialsByKeysQueryOpParams
) => {
	return axiosClient<GardenPartialSchema[]>({
		url: `/gardens/query/partials_by_key`,
		method: 'GET',
		params
	});
};
/**
 * Returns a set of tuples of gardens and associated pending garden memberships
 * @summary Returns a set of pending garden invites
 */
export const gardenPendingInvitesQueryOp = () => {
	return axiosClient<GardenPendingInvitesResult>({
		url: `/gardens/query/pending_invites`,
		method: 'GET'
	});
};
export type GardenMembershipAcceptCommandOpResult = NonNullable<
	Awaited<ReturnType<typeof gardenMembershipAcceptCommandOp>>
>;
export type GardenMembershipRoleChangeCommandOpResult = NonNullable<
	Awaited<ReturnType<typeof gardenMembershipRoleChangeCommandOp>>
>;
export type GardenCreateCommandOpResult = NonNullable<
	Awaited<ReturnType<typeof gardenCreateCommandOp>>
>;
export type GardenMembershipCreateCommandOpResult = NonNullable<
	Awaited<ReturnType<typeof gardenMembershipCreateCommandOp>>
>;
export type GardenMembershipDeleteCommandOpResult = NonNullable<
	Awaited<ReturnType<typeof gardenMembershipDeleteCommandOp>>
>;
export type GardenMembershipRevokeCommandOpResult = NonNullable<
	Awaited<ReturnType<typeof gardenMembershipRevokeCommandOp>>
>;
export type GardenAssociatedPartialsQueryOpResult = NonNullable<
	Awaited<ReturnType<typeof gardenAssociatedPartialsQueryOp>>
>;
export type GardenFullByKeyQueryOpResult = NonNullable<
	Awaited<ReturnType<typeof gardenFullByKeyQueryOp>>
>;
export type GardenGenerateUniqueKeyQueryOpResult = NonNullable<
	Awaited<ReturnType<typeof gardenGenerateUniqueKeyQueryOp>>
>;
export type GardenMostRelevantPartialsQueryOpResult = NonNullable<
	Awaited<ReturnType<typeof gardenMostRelevantPartialsQueryOp>>
>;
export type GardenPartialsByKeysQueryOpResult = NonNullable<
	Awaited<ReturnType<typeof gardenPartialsByKeysQueryOp>>
>;
export type GardenPendingInvitesQueryOpResult = NonNullable<
	Awaited<ReturnType<typeof gardenPendingInvitesQueryOp>>
>;
