# Generated by Django 4.1.5 on 2023-03-23 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('string_id', models.CharField(max_length=75, unique=True, verbose_name='unique sting identifier')),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted'), ('PUBLIC', 'Public')], default='PRIVATE', help_text='Public gardens are view accessible to anyone with a link and anyone who has been explicitly added and can appear elsewhere publicly on the app. Unlisted gardens are view accessible to anyone with a link and anyone who has been explicitly added but cannot appear elsewhere publicly on the site. Private gardens are view accessible only to anyone that is explicitly invited.', max_length=8, verbose_name='visibility')),
                ('timezone', timezone_field.fields.TimeZoneField(blank=True, null=True, verbose_name='timezone')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
                ('long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude coordinate')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude coordinate')),
                ('admins', models.ManyToManyField(help_text='Admin users have the following permisions in a Garden: Garden settings update, Admin, editor, viewer list: create, update and delete, Workspaces create and delete, Devices create, update, and delete, ModelOutput control.', related_name='admin_gardens', to=settings.AUTH_USER_MODEL, verbose_name='garden_admins')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gardens', to=settings.AUTH_USER_MODEL, verbose_name='creator user')),
                ('editors', models.ManyToManyField(help_text='Editor users have the following permisions in a Garden: Garden viewers create, Planting scheme create, update, and delete, HarvestEntry create, update, and delete, ModelInputEntry create, update, and delete.', related_name='edit_gardens', to=settings.AUTH_USER_MODEL, verbose_name='garden_editors')),
                ('viewers', models.ManyToManyField(help_text='Viewer users have read-only permisions in a Garden', related_name='view_gardens', to=settings.AUTH_USER_MODEL, verbose_name='garden_viewers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
