# Generated by Django 4.1.5 on 2023-05-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='garden',
            constraint=models.UniqueConstraint(fields=('name', 'creator'), name='unique_garden_name_among_user_created_gardens'),
        ),
    ]
