# Generated by Django 4.1.5 on 2023-05-28 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardens', '0002_garden_unique_garden_name_among_user_created_gardens'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=6, verbose_name='role')),
                ('invite_open', models.BooleanField(default=True, verbose_name='closed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='GardenInvite',
        ),
        migrations.RemoveConstraint(
            model_name='garden',
            name='unique_garden_name_among_user_created_gardens',
        ),
        migrations.RemoveField(
            model_name='garden',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='garden',
            name='editors',
        ),
        migrations.RemoveField(
            model_name='garden',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='garden',
            name='viewers',
        ),
        migrations.AddField(
            model_name='gardenmembership',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent_from', to='gardens.garden', verbose_name='garden'),
        ),
        migrations.AddField(
            model_name='gardenmembership',
            name='inviter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='inviter'),
        ),
        migrations.AddField(
            model_name='gardenmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='garden',
            name='users',
            field=models.ManyToManyField(related_name='user_gardens', through='gardens.GardenMembership', to=settings.AUTH_USER_MODEL, verbose_name='garden users'),
        ),
    ]
