# Generated by Django 4.1.5 on 2023-05-28 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_gardenmembership_delete_gardeninvite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenmembership',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gardens.garden', verbose_name='garden'),
        ),
    ]
