# Generated by Django 4.1.5 on 2023-05-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0004_alter_gardenmembership_garden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenmembership',
            name='invite_open',
        ),
        migrations.AddField(
            model_name='gardenmembership',
            name='open_invite',
            field=models.BooleanField(default=True, verbose_name='open invite'),
        ),
    ]
