# Generated by Django 4.1.5 on 2023-06-01 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0005_remove_gardenmembership_invite_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenmembership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EDIT', 'Editor'), ('VIEW', 'Viewer')], default='VIEW', max_length=6, verbose_name='role'),
        ),
    ]
