# Generated by Django 4.1.5 on 2023-06-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0006_alter_gardenmembership_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='gardenmembership',
            constraint=models.UniqueConstraint(fields=('user', 'garden'), name='user_unique_in_garden'),
        ),
    ]
