# Generated by Django 4.1.5 on 2023-06-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0007_gardenmembership_user_unique_in_garden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='string_id',
        ),
        migrations.AddField(
            model_name='garden',
            name='hashid',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
