/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type {
	CultivarAttributeUpdateCommand,
	CultivarCollectionFullSchema,
	CultivarCollectionGetByClientResult,
	CultivarCollectionGetByGardenQueryOpParams,
	CultivarCollectionGetByGardenResult,
	CultivarCollectionGetByIdsQueryOpParams
} from '../../types';
import { axiosClient } from '../../../data/customAxios';

/**
 * Sets the given attributes onto the cultivar.
 * @summary Cultivar update.
 */
export const cultivarAttributeUpdateCommandOp = (
	cultivarAttributeUpdateCommand: CultivarAttributeUpdateCommand
) => {
	return axiosClient<string>({
		url: `/cultivars/command/update`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: cultivarAttributeUpdateCommand
	});
};
/**
 * Retrieves the cultivar collections associated with this garden.
 * @summary Get cultivar collections from a garden.
 */
export const cultivarGetByClientQueryOp = () => {
	return axiosClient<CultivarCollectionGetByClientResult>({
		url: `/cultivars/query/get_by_client`,
		method: 'GET'
	});
};
/**
 * Retrieves the cultivar collections associated with this garden.
 * @summary Get cultivar collections from a garden.
 */
export const CultivarCollectionGetByGardenQueryOp = (
	params: CultivarCollectionGetByGardenQueryOpParams
) => {
	return axiosClient<CultivarCollectionGetByGardenResult>({
		url: `/cultivars/query/get_by_garden`,
		method: 'GET',
		params
	});
};
/**
 * Retrieves the cultivar collections associated with the IDs.
 * @summary Get cultivar collections from their IDs.
 */
export const CultivarCollectionGetByIdsQueryOp = (params: CultivarCollectionGetByIdsQueryOpParams) => {
	return axiosClient<CultivarCollectionFullSchema[]>({
		url: `/cultivars/query/get_by_ids`,
		method: 'GET',
		params
	});
};
export type CultivarAttributeUpdateCommandOpResult = NonNullable<
	Awaited<ReturnType<typeof cultivarAttributeUpdateCommandOp>>
>;
export type CultivarGetByClientQueryOpResult = NonNullable<
	Awaited<ReturnType<typeof cultivarGetByClientQueryOp>>
>;
export type CultivarCollectionGetByGardenQueryOpResult = NonNullable<
	Awaited<ReturnType<typeof CultivarCollectionGetByGardenQueryOp>>
>;
export type CultivarCollectionGetByIdsQueryOpResult = NonNullable<
	Awaited<ReturnType<typeof CultivarCollectionGetByIdsQueryOp>>
>;
