"""

Revision ID: 0e9c3707c98e
Revises: 94e284f9646d
Create Date: 2023-11-05 18:36:26.229993

"""
# Standard Library
from typing import Sequence, Union

# External Libraries
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0e9c3707c98e'
down_revision: Union[str, None] = '94e284f9646d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username_norm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username_norm', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
