"""

Revision ID: 541cb0016ef0
Revises: 
Create Date: 2023-10-12 22:16:01.362534

"""
# Standard Library
from typing import Sequence, Union

# External Libraries
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '541cb0016ef0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('username_norm', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('password_reset_confirmation_key', sa.String(length=64), nullable=True),
    sa.Column('password_reset_confirmation_created_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_email',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('list_index', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.Column('confirmation_key', sa.String(length=64), nullable=True),
    sa.Column('confirmation_created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'list_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_email')
    op.drop_table('user')
    # ### end Alembic commands ###
