"""

Revision ID: 94e284f9646d
Revises: ab7c828c5f00
Create Date: 2023-11-03 18:56:43.292049

"""
# Standard Library
from typing import Sequence, Union

# External Libraries

# revision identifiers, used by Alembic.
revision: str = '94e284f9646d'
down_revision: Union[str, None] = 'ab7c828c5f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
