/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type {
	PlantingAreaCreateCommand,
	PlantingAreaDeleteCommand,
	PlantingAreaUpdateCommand,
	WorkspaceCreateCommand,
	WorkspaceDeleteCommand,
	WorkspaceFullSchema,
	WorkspaceGetFullQueryOpParams,
	WorkspaceGetPartialsQueryOpParams,
	WorkspacePartialSchema,
	WorkspaceUpdateCommand
} from '../../types';
import { axiosClient } from '../../../data/customAxios';

/**
 * Creates a new planting area on the workspace.
 * @summary Planting area create.
 */
export const plantingAreaCreateCommandOp = (
	plantingAreaCreateCommand: PlantingAreaCreateCommand
) => {
	return axiosClient<string>({
		url: `/workspaces/command/create_planting_area`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: plantingAreaCreateCommand
	});
};
/**
 * Creates a new workspace on the garden.
 * @summary Workspace create.
 */
export const workspaceCreateCommandOp = (
	workspaceCreateCommand: WorkspaceCreateCommand
) => {
	return axiosClient<string>({
		url: `/workspaces/command/create_workspace`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: workspaceCreateCommand
	});
};
/**
 * Deletes a given planting area from a workspace.
 * @summary Planting area delete.
 */
export const plantingAreaDeleteCommandOp = (
	plantingAreaDeleteCommand: PlantingAreaDeleteCommand
) => {
	return axiosClient<string>({
		url: `/workspaces/command/delete_planting_area`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: plantingAreaDeleteCommand
	});
};
/**
 * Deletes a given workspace from a garden.
 * @summary Workspace delete.
 */
export const workspaceDeleteCommandOp = (
	workspaceDeleteCommand: WorkspaceDeleteCommand
) => {
	return axiosClient<string>({
		url: `/workspaces/command/delete_workspace`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: workspaceDeleteCommand
	});
};
/**
 * Sets the given attributes onto the planting area.
 * @summary Planting area update.
 */
export const plantingAreaUpdateCommandOp = (
	plantingAreaUpdateCommand: PlantingAreaUpdateCommand
) => {
	return axiosClient<string>({
		url: `/workspaces/command/update_planting_area`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: plantingAreaUpdateCommand
	});
};
/**
 * Sets the given attributes onto the workspace.
 * @summary Workspace update.
 */
export const workspaceUpdateCommandOp = (
	workspaceUpdateCommand: WorkspaceUpdateCommand
) => {
	return axiosClient<string>({
		url: `/workspaces/command/update_workspace`,
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		data: workspaceUpdateCommand
	});
};
/**
 * Retrieves a full workspace schema.
 * @summary Get a full workspace schema.
 */
export const workspaceGetFullQueryOp = (params: WorkspaceGetFullQueryOpParams) => {
	return axiosClient<WorkspaceFullSchema>({
		url: `/workspaces/query/get_full`,
		method: 'GET',
		params
	});
};
/**
 * Retrieves the workspaces associated with this garden.
 * @summary Get workspaces from a garden.
 */
export const workspaceGetPartialsQueryOp = (
	params: WorkspaceGetPartialsQueryOpParams
) => {
	return axiosClient<WorkspacePartialSchema[]>({
		url: `/workspaces/query/get_partials`,
		method: 'GET',
		params
	});
};
export type PlantingAreaCreateCommandOpResult = NonNullable<
	Awaited<ReturnType<typeof plantingAreaCreateCommandOp>>
>;
export type WorkspaceCreateCommandOpResult = NonNullable<
	Awaited<ReturnType<typeof workspaceCreateCommandOp>>
>;
export type PlantingAreaDeleteCommandOpResult = NonNullable<
	Awaited<ReturnType<typeof plantingAreaDeleteCommandOp>>
>;
export type WorkspaceDeleteCommandOpResult = NonNullable<
	Awaited<ReturnType<typeof workspaceDeleteCommandOp>>
>;
export type PlantingAreaUpdateCommandOpResult = NonNullable<
	Awaited<ReturnType<typeof plantingAreaUpdateCommandOp>>
>;
export type WorkspaceUpdateCommandOpResult = NonNullable<
	Awaited<ReturnType<typeof workspaceUpdateCommandOp>>
>;
export type WorkspaceGetFullQueryOpResult = NonNullable<
	Awaited<ReturnType<typeof workspaceGetFullQueryOp>>
>;
export type WorkspaceGetPartialsQueryOpResult = NonNullable<
	Awaited<ReturnType<typeof workspaceGetPartialsQueryOp>>
>;
