/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type {
	WorkspaceFullSchema,
	WorkspaceGetFullQueryOpParams,
	WorkspaceGetPartialsQueryOpParams,
	WorkspacePartialSchema
} from '../../types';
import { axiosClient } from '../../../data/customAxios';

/**
 * Retrieves a full workspace schema.
 * @summary Get a full workspace schema.
 */
export const workspaceGetFullQueryOp = (params: WorkspaceGetFullQueryOpParams) => {
	return axiosClient<WorkspaceFullSchema>({
		url: `/workspaces/query/get_full`,
		method: 'GET',
		params
	});
};
/**
 * Retrieves the workspaces associated with this garden.
 * @summary Get workspaces from a garden.
 */
export const workspaceGetPartialsQueryOp = (
	params: WorkspaceGetPartialsQueryOpParams
) => {
	return axiosClient<WorkspacePartialSchema[]>({
		url: `/workspaces/query/get_partials`,
		method: 'GET',
		params
	});
};
export type WorkspaceGetFullQueryOpResult = NonNullable<
	Awaited<ReturnType<typeof workspaceGetFullQueryOp>>
>;
export type WorkspaceGetPartialsQueryOpResult = NonNullable<
	Awaited<ReturnType<typeof workspaceGetPartialsQueryOp>>
>;
