"""

Revision ID: 5685efaef278
Revises: 
Create Date: 2024-07-12 04:13:25.573110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5685efaef278'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garden_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('creator_ref_id', sa.Uuid(), nullable=True),
    sa.Column('visibility', sa.Enum('PRIVATE', 'UNLISTED', 'PUBLIC', name='visibilityenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('password_reset_confirmation_key', sa.Uuid(), nullable=True),
    sa.Column('password_reset_confirmation_created_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('garden_membership_table',
    sa.Column('garden_id', sa.Uuid(), nullable=False),
    sa.Column('user_ref_id', sa.Uuid(), nullable=False),
    sa.Column('inviter_ref_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'EDIT', 'VIEW', name='roleenum'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['garden_id'], ['garden_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('garden_id', 'user_ref_id')
    )
    op.create_table('user_email_table',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.Column('confirmation_key', sa.Uuid(), nullable=True),
    sa.Column('confirmation_created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'address'),
    sa.UniqueConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_email_table')
    op.drop_table('garden_membership_table')
    op.drop_table('user_table')
    op.drop_table('garden_table')
    # ### end Alembic commands ###
