"""

Revision ID: 83548e0fc47d
Revises: 89a4d2d42cd9
Create Date: 2024-07-04 06:14:42.445634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83548e0fc47d'
down_revision: Union[str, None] = '89a4d2d42cd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_email_table', '_list_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_email_table', sa.Column('_list_index', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
