"""

Revision ID: 99c189813fa0
Revises: d1b39f469df3
Create Date: 2024-06-29 08:42:37.054776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c189813fa0'
down_revision: Union[str, None] = 'd1b39f469df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('password_reset_confirmation_key', sa.Uuid(), nullable=True),
    sa.Column('password_reset_confirmation_created_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_email_table',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('_list_index', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.Column('confirmation_key', sa.Uuid(), nullable=True),
    sa.Column('confirmation_created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', '_list_index'),
    sa.UniqueConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_email_table')
    op.drop_table('users')
    # ### end Alembic commands ###
