"""

Revision ID: f32c42f2210f
Revises: 7dc3e3e90949
Create Date: 2023-10-15 01:33:40.327170

"""
# Standard Library
from typing import Sequence, Union

# External Libraries

# revision identifiers, used by Alembic.
revision: str = 'f32c42f2210f'
down_revision: Union[str, None] = '7dc3e3e90949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
