/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */

export enum _OriginProfileAllowedOriginsOneOfItem {
	direct_seed = 'direct seed',
	seed_transplant = 'seed transplant',
	seedling_transplant = 'seedling transplant'
}
