/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type { CultivarCollectionUpdateCommandDescription } from './cultivarCollectionUpdateCommandDescription';
import type { CultivarCollectionUpdateCommandName } from './cultivarCollectionUpdateCommandName';
import type { CultivarCollectionUpdateCommandParentRef } from './cultivarCollectionUpdateCommandParentRef';
import type { CultivarCollectionUpdateCommandTags } from './cultivarCollectionUpdateCommandTags';
import type { CultivarCollectionUpdateCommandVisibility } from './cultivarCollectionUpdateCommandVisibility';

export interface CultivarCollectionUpdateCommand {
	collection_ref: string;
	description?: CultivarCollectionUpdateCommandDescription;
	name?: CultivarCollectionUpdateCommandName;
	parent_ref?: CultivarCollectionUpdateCommandParentRef;
	remove_parent?: boolean;
	tags?: CultivarCollectionUpdateCommandTags;
	visibility?: CultivarCollectionUpdateCommandVisibility;
}
