/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type { CultivarSchema } from './cultivarSchema';
import type { CultivarCollectionFullSchemaDescription } from './cultivarCollectionFullSchemaDescription';
import type { CultivarCollectionFullSchemaGardenRef } from './cultivarCollectionFullSchemaGardenRef';
import type { CultivarCollectionFullSchemaParentRef } from './cultivarCollectionFullSchemaParentRef';
import type { CultivarCollectionFullSchemaUserRef } from './cultivarCollectionFullSchemaUserRef';

export interface CultivarCollectionFullSchema {
	cultivars: CultivarSchema[];
	description?: CultivarCollectionFullSchemaDescription;
	garden_ref?: CultivarCollectionFullSchemaGardenRef;
	id: string;
	key: string;
	name: string;
	parent_ref?: CultivarCollectionFullSchemaParentRef;
	tags: string[];
	user_ref?: CultivarCollectionFullSchemaUserRef;
}
