/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type { CultivarAttributeSet } from './cultivarAttributeSet';
import type { CultivarSchemaParentId } from './cultivarSchemaParentId';

export interface CultivarSchema {
	attributes: CultivarAttributeSet;
	created_at: string;
	description: string;
	id: string;
	key: string;
	name: string;
	names: string[];
	parent_id?: CultivarSchemaParentId;
	scientific_name: string;
}
