/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type { CultivarAttributeProfileSet } from './cultivarAttributeProfileSet'
import type { CultivarId } from './cultivarId'
import type { CultivarParentId } from './cultivarParentId'

export interface Cultivar {
	abbreviation: string
	attributes?: CultivarAttributeProfileSet
	created_at?: string
	id?: CultivarId
	name: string
	parent_id?: CultivarParentId
}
