/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type { CultivarCreateCommandDescription } from './cultivarCreateCommandDescription';
import type { CultivarCreateCommandKey } from './cultivarCreateCommandKey';
import type { CultivarCreateCommandParentId } from './cultivarCreateCommandParentId';
import type { CultivarCreateCommandScientificName } from './cultivarCreateCommandScientificName';

export interface CultivarCreateCommand {
	collection_ref: string;
	description?: CultivarCreateCommandDescription;
	key?: CultivarCreateCommandKey;
	/**
	 * A set of common names associated with this plant species. Each name must be between 3 and 30 characters long and contain only alphanumeric characters and spaces. There must be at least 1 name and a maximum of 10 names
	 * @maxLength 10
	 */
	names: string[];
	parent_id?: CultivarCreateCommandParentId;
	scientific_name?: CultivarCreateCommandScientificName;
}
