/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type { CultivarAttributeSetFrostDatePlantingWindows } from './cultivarAttributeSetFrostDatePlantingWindows'
import type { CultivarAttributeSetLifecycle } from './cultivarAttributeSetLifecycle'
import type { CultivarAttributeSetOrigin } from './cultivarAttributeSetOrigin'

export interface CultivarAttributeSet {
	frost_date_planting_windows?: CultivarAttributeSetFrostDatePlantingWindows
	lifecycle?: CultivarAttributeSetLifecycle
	origin?: CultivarAttributeSetOrigin
}
