/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type { CultivarCollectionPartialSchemaGardenRef } from './cultivarCollectionPartialSchemaGardenRef';
import type { CultivarCollectionPartialSchemaParentRef } from './cultivarCollectionPartialSchemaParentRef';
import type { CultivarCollectionPartialSchemaUserRef } from './cultivarCollectionPartialSchemaUserRef';
import type { CultivarCollectionPartialSchemaVisibility } from './cultivarCollectionPartialSchemaVisibility';

export interface CultivarCollectionPartialSchema {
	created_at: string;
	description: string;
	garden_ref?: CultivarCollectionPartialSchemaGardenRef;
	id: string;
	name: string;
	parent_ref?: CultivarCollectionPartialSchemaParentRef;
	slug: string;
	tags: string[];
	user_ref?: CultivarCollectionPartialSchemaUserRef;
	visibility: CultivarCollectionPartialSchemaVisibility;
}
