/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */

export interface GardenMembershipCreateCommand {
	/**
	 * A maximum of 10 users can be invited at once
	 * @maxLength 10
	 */
	admin_usernames?: string[];
	/**
	 * A maximum of 10 users can be invited at once
	 * @maxLength 10
	 */
	editor_usernames?: string[];
	garden_id: string;
	/**
	 * A maximum of 10 users can be invited at once
	 * @maxLength 10
	 */
	viewer_usernames?: string[];
}
