/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type { GardenPartialSchema } from './gardenPartialSchema';

export interface GardenAssociatedPartialsResult {
	admin_memberships: string[];
	edit_memberships: string[];
	favorites: string[];
	gardens: GardenPartialSchema[];
	view_memberships: string[];
}
