/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type { RefSchema } from './refSchema'
import type { GardenMembershipFullSchemaInviterRef } from './gardenMembershipFullSchemaInviterRef'
import type { GardenMembershipFullSchemaRole } from './gardenMembershipFullSchemaRole'

export interface GardenMembershipFullSchema {
	accepted: boolean
	created_at: string
	favorite: boolean
	garden_ref: RefSchema
	inviter_ref?: GardenMembershipFullSchemaInviterRef
	role: GardenMembershipFullSchemaRole
	user_ref: RefSchema
}
