/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type { GeometryCreateUpdateCommandEllipseAttributes } from './geometryCreateUpdateCommandEllipseAttributes';
import type { GeometryCreateUpdateCommandLinesAttributes } from './geometryCreateUpdateCommandLinesAttributes';
import type { GeometryCreateUpdateCommandPolygonAttributes } from './geometryCreateUpdateCommandPolygonAttributes';
import type { GeometryCreateUpdateCommandRectangleAttributes } from './geometryCreateUpdateCommandRectangleAttributes';
import type { GeometryCreateUpdateCommandScaleFactor } from './geometryCreateUpdateCommandScaleFactor';
import type { GeometryCreateUpdateCommandType } from './geometryCreateUpdateCommandType';

export interface GeometryCreateUpdateCommand {
	ellipse_attributes?: GeometryCreateUpdateCommandEllipseAttributes;
	lines_attributes?: GeometryCreateUpdateCommandLinesAttributes;
	polygon_attributes?: GeometryCreateUpdateCommandPolygonAttributes;
	rectangle_attributes?: GeometryCreateUpdateCommandRectangleAttributes;
	scale_factor?: GeometryCreateUpdateCommandScaleFactor;
	type: GeometryCreateUpdateCommandType;
}
