/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type { GeometryCreateUpdateCommand } from './geometryCreateUpdateCommand';
import type { GeometricHistoryPointCreateUpdateCommandTime } from './geometricHistoryPointCreateUpdateCommandTime';

export interface GeometricHistoryPointCreateUpdateCommand {
	geometry: GeometryCreateUpdateCommand;
	time?: GeometricHistoryPointCreateUpdateCommandTime;
}
