/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type { GeometrySchemaAttributes } from './geometrySchemaAttributes';
import type { GeometrySchemaType } from './geometrySchemaType';

export interface GeometrySchema {
	attributes: GeometrySchemaAttributes;
	nulled: boolean;
	rotation: number;
	scale_factor: number;
	type: GeometrySchemaType;
}
