/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type { LifecycleProfileFirstToLastHarvest } from './lifecycleProfileFirstToLastHarvest'
import type { LifecycleProfileGermToSprout } from './lifecycleProfileGermToSprout'
import type { LifecycleProfileGermToTransplant } from './lifecycleProfileGermToTransplant'
import type { LifecycleProfileLastHarvestToExpiry } from './lifecycleProfileLastHarvestToExpiry'
import type { LifecycleProfileSowToGerm } from './lifecycleProfileSowToGerm'
import type { LifecycleProfileSproutToFirstHarvest } from './lifecycleProfileSproutToFirstHarvest'
import type { LifecycleProfileYearsOfLife } from './lifecycleProfileYearsOfLife'

export interface LifecycleProfile {
	first_to_last_harvest?: LifecycleProfileFirstToLastHarvest
	germ_to_sprout?: LifecycleProfileGermToSprout
	germ_to_transplant?: LifecycleProfileGermToTransplant
	last_harvest_to_expiry?: LifecycleProfileLastHarvestToExpiry
	sow_to_germ?: LifecycleProfileSowToGerm
	sprout_to_first_harvest?: LifecycleProfileSproutToFirstHarvest
	years_of_life?: LifecycleProfileYearsOfLife
}
