/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */

export interface UserPasswordVerificationQuery {
	email_address: string;
	/**
	 * Must be between 6 and 255 characters long and contain at least one lowercase letter, one uppercase letter, one digit, and one special character
	 * @minLength 6
	 * @maxLength 255
	 * @pattern ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*\W).*$
	 */
	password: string;
}
