/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type { EmailSchema } from './emailSchema'

export interface UserFullSchema {
	created_at: string
	emails: EmailSchema[]
	id: string
	is_superuser: boolean
	username: string
}
