/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * VerdanTech-Backend
 * Backend API of the VerdanTech software project.
 * OpenAPI spec version: 0.1.0
 */
import type { WorkspaceUpdateCommandDescription } from './workspaceUpdateCommandDescription';
import type { WorkspaceUpdateCommandName } from './workspaceUpdateCommandName';

export interface WorkspaceUpdateCommand {
	description?: WorkspaceUpdateCommandDescription;
	name?: WorkspaceUpdateCommandName;
	workspace_ref: string;
}
