"""

Revision ID: 418589ee2855
Revises: c2f25152957c
Create Date: 2023-10-15 01:49:18.217258

"""
# Standard Library
from typing import Sequence, Union

# External Libraries
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '418589ee2855'
down_revision: Union[str, None] = 'c2f25152957c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
