"""

Revision ID: ab7c828c5f00
Revises: 7e8b7fb5bc2e
Create Date: 2023-11-03 18:44:49.720313

"""
# Standard Library
from typing import Sequence, Union

# External Libraries
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ab7c828c5f00'
down_revision: Union[str, None] = '7e8b7fb5bc2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
