"""

Revision ID: aa1209b7d1b4
Revises: 418589ee2855
Create Date: 2023-10-15 02:04:52.621232

"""
# Standard Library
from typing import Sequence, Union

# External Libraries
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aa1209b7d1b4'
down_revision: Union[str, None] = '418589ee2855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
