"""

Revision ID: c2f25152957c
Revises: f32c42f2210f
Create Date: 2023-10-15 01:45:32.533487

"""
# Standard Library
from typing import Sequence, Union

# External Libraries

# revision identifiers, used by Alembic.
revision: str = 'c2f25152957c'
down_revision: Union[str, None] = 'f32c42f2210f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
