/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * VerdanTech-API
 * API of the VerdanTech Project Web Application
 * OpenAPI spec version: 0.1.0
 */
export interface VerifyEmailRequest {
	key: string;
}

export interface RestAuthDetail {
	readonly detail: string;
}

export interface ResendEmailVerificationRequest {
	email: string;
}

export interface ResendEmailVerification {
	email: string;
}

export interface RegisterRequest {
	username: string;
	email: string;
	password1: string;
	password2: string;
}

export interface Register {
	username: string;
	email: string;
}

/**
 * Serializer for requesting a password reset e-mail.
 */
export interface PasswordResetRequest {
	email: string;
}

/**
 * Serializer for confirming a password reset attempt.
 */
export interface PasswordResetConfirmRequest {
	new_password1: string;
	new_password2: string;
	uid: string;
	token: string;
}

/**
 * Serializer for confirming a password reset attempt.
 */
export interface PasswordResetConfirm {
	new_password1: string;
	new_password2: string;
	uid: string;
	token: string;
}

/**
 * Serializer for requesting a password reset e-mail.
 */
export interface PasswordReset {
	email: string;
}

export interface PasswordChangeRequest {
	new_password1: string;
	new_password2: string;
}

export interface LoginRequest {
	email: string;
	password: string;
}

export interface Login {
	email: string;
	password: string;
}

export interface CSRFToken {
	csrftoken: string;
}
